#%RAML 0.8
title: BetterForms Form API
version: v1
baseUri: http://base
schemas:
baseUriParameters:
documentation:
 - title: Home
   content: |
     This is the BetterForms Submission Service API.

/submissions/{formId}:
  post:
   description: Submits the form with the given ID to its default submission target (note the form to submit is *not* given in the body; the body should be empty and will be ignored).  The form must already exist in the store (via a POST to /forms).
   responses:
       200:
         description: Successful submission.  Note this does not indicate that any resultant processing of the form will be successful.  Check subimssion status using GET to this URL.

  get:
   description: Gets the submission status of the form with the given ID.  The service may use Track & Trace to retrieve submission status.
   responses:
      200:
        description: JSON containing information on where the form has been sent and what has been done with it.
