#%RAML 0.8
title: BetterForms Admin API
version: v1
#baseUri: http://base
baseUri: https://mocksvc.mulesoft.com/mocks/337b085c-9aa9-4e2c-b489-b86fbf2f5bc1
schemas:
baseUriParameters:
documentation:
 - title: Home
   content: |
     This is the BetterForms Admin service API.
/users:
  get:
    description: Lists all the users you are authorized to view
